# Generated by Django 5.2.3 on 2025-07-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_no', models.IntegerField(default=0)),
                ('d_line_1', models.TextField(max_length=500)),
                ('d_line_2', models.TextField(max_length=500)),
                ('d_line_3', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_no', models.IntegerField(default=0)),
                ('l_name', models.CharField(max_length=50)),
                ('l_img', models.ImageField(upload_to='')),
                ('l_link', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_no', models.IntegerField(default=0)),
                ('p_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
